# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ddc33cf0df29e0f847ebcae0ace54cdeb912aa0172487d584a4989cadcf55f07535da5c6519684b3cdd158b2d08731403bd730b6305b4987b47aa5b3b7366a52

test:
  secret_key_base: fe755b757e35e6568717079db4dc58eaaca65c0df4c31d5ae3932e36934ce57882df21ffeb79048eb5ef7a2a5abacb39567964fe0ccdf57374251fcf6c350347

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
